# @package _global_
defaults:
  - /extract/backblaze/base@_here_

bucket_name: timkpaine-public
object_key: projects/pkn/superstore.csv
format: text
output_name: superstore
suffix: .csv

# pkn-cc +context=[] +extract=backblaze/example
