# @package _global_
defaults:
  - /extract/backblaze/base@_here_

bucket_name: timkpaine-public
object_key: projects/pkn/superstore.csv
format: text
output_name: superstore
suffix: .csv

# pkn-cc +context=[2025-01-01,2025-01-31,[],forward,2D] +extract=backblaze/example_backfill

backfill:
  _target_: pkn.ccflow.BackfillModel
  model: ${..read}

cli:
  model:
    _target_: ccflow.FlowOptions
    evaluator:
      _target_: ccflow.evaluators.GraphEvaluator
    cacheable: true

callable: /backfill
